//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS_V4_SAP_integration.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SQLScript {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQLScript() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PMS_V4_SAP_integration.Resources.SQLScript", typeof(SQLScript).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;with ctel as
        ///(
        ///	select TD.sk_hdr, TH.draw as ProjectCode, TD.price as UnitPrice, sum(qty) as Quantity, round(TD.price * sum(qty), 2) as DocTotal
        ///	, &apos;D&apos; + left(TH.draw,2) as ItemCode , &apos;X0S&apos; as VatGroup
        ///	from invoice_dtl TD inner join invoice TH on TH.sk_hdr = TD.sk_hdr
        ///	where TH.postflag = 0 and TH.chkflag = 1
        ///	group by TD.sk_hdr, TH.draw, TD.price
        ///)
        ///, ctes as
        ///(
        ///	select TD.sk_hdr, TH.draw as ProjectCode, round(ctel.DocTotal * TS.extrastpct / 100,2) as UnitPrice, 1 as Quantity
        ///	, TS.TaxItemCode a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Invoice_posting_script {
            get {
                return ResourceManager.GetString("Invoice_posting_script", resourceCulture);
            }
        }
    }
}
